# Generated by Django 4.1.7 on 2023-03-17 06:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_nam', models.CharField(max_length=20, unique=True)),
                ('image', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20, unique=True)),
                ('password', models.CharField(max_length=20)),
                ('usertype', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pro_name', models.CharField(max_length=25)),
                ('details', models.CharField(max_length=300)),
                ('price', models.CharField(max_length=10)),
                ('image', models.ImageField(upload_to='')),
                ('place', models.CharField(max_length=30)),
                ('date', models.CharField(max_length=20)),
                ('time', models.CharField(max_length=20)),
                ('status', models.CharField(max_length=25)),
                ('catg', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminpart.category')),
            ],
        ),
        migrations.CreateModel(
            name='registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lastname', models.CharField(max_length=20)),
                ('firstname', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=10)),
                ('phone', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=30)),
                ('login', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminpart.login')),
            ],
        ),
        migrations.CreateModel(
            name='wishlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminpart.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminpart.registration')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminpart.registration'),
        ),
        migrations.CreateModel(
            name='notif',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification', models.CharField(max_length=100)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminpart.product')),
            ],
        ),
        migrations.CreateModel(
            name='chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doubt', models.CharField(max_length=300)),
                ('reply', models.CharField(max_length=300)),
                ('cdate', models.DateField()),
                ('ctime', models.TimeField()),
                ('fid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fid', to='adminpart.registration')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminpart.product')),
                ('tid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tid', to='adminpart.registration')),
            ],
        ),
    ]
