# Generated by Django 4.1.7 on 2023-02-26 06:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminpart', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registration',
            old_name='loginid',
            new_name='login',
        ),
    ]
