# Generated by Django 4.1.7 on 2023-02-27 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpart', '0002_rename_loginid_registration_login'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category_nam',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
