# Generated by Django 4.1.7 on 2023-03-24 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpart', '0002_register_auction'),
    ]

    operations = [
        migrations.AddField(
            model_name='register_auction',
            name='status',
            field=models.CharField(default=0, max_length=15),
            preserve_default=False,
        ),
    ]
