# Generated by Django 4.1.7 on 2023-03-04 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpart', '0003_alter_category_category_nam'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='phone',
            field=models.CharField(max_length=15),
        ),
    ]
