# Generated by Django 4.1.7 on 2023-03-06 23:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminpart', '0004_alter_registration_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pro_name', models.CharField(max_length=25)),
                ('details', models.CharField(max_length=300)),
                ('price', models.IntegerField(max_length=15)),
                ('image', models.ImageField(upload_to='')),
                ('place', models.CharField(max_length=30)),
                ('status', models.CharField(max_length=25)),
                ('catg', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminpart.category')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminpart.registration')),
            ],
        ),
    ]
