# Generated by Django 4.1.7 on 2023-04-04 07:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminpart', '0004_notf'),
    ]

    operations = [
        migrations.CreateModel(
            name='bid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amt', models.CharField(max_length=20)),
                ('adate', models.DateField()),
                ('atime', models.TimeField()),
                ('status', models.CharField(max_length=20)),
                ('pid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminpart.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminpart.registration')),
            ],
        ),
    ]
