# Generated by Django 4.1.7 on 2023-04-04 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpart', '0006_auction'),
    ]

    operations = [
        migrations.RenameField(
            model_name='auction',
            old_name='bids',
            new_name='pid',
        ),
        migrations.AddField(
            model_name='auction',
            name='flag',
            field=models.CharField(default=1, max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='auction',
            name='time',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
