# Generated by Django 4.1.7 on 2023-03-07 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpart', '0007_alter_product_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='login',
            name='username',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
