# Generated by Django 4.1.7 on 2023-04-04 10:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminpart', '0007_rename_bids_auction_pid_auction_flag_auction_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='pid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminpart.product'),
        ),
    ]
