# Generated by Django 4.1.7 on 2023-03-07 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpart', '0008_alter_login_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='date',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='time',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
    ]
