# Generated by Django 4.1.7 on 2023-04-27 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpart', '0009_pay'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='rprice',
            field=models.CharField(default=0, max_length=10),
            preserve_default=False,
        ),
    ]
