# Generated by Django 4.1.7 on 2023-04-28 07:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminpart', '0010_product_rprice'),
    ]

    operations = [
        migrations.CreateModel(
            name='rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review', models.CharField(max_length=200)),
                ('rate', models.FloatField()),
                ('by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='by', to='adminpart.registration')),
                ('sl', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sl', to='adminpart.registration')),
            ],
        ),
    ]
