# Generated by Django 4.1.7 on 2023-05-05 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpart', '0012_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='pay',
            name='date',
            field=models.DateField(default="2000-10-26"),
            preserve_default=False,
        ),
    ]
